#!C:\Users\brahmeswara.d\anaconda3\python.exe
import cgi
print('Content-type:text/html\n')
print('''
<html><head><title>My First CGI Script</title></head>
<body><h1>Hello World</h1></body></html>
''')
